# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Adminmenu_img.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Adminmenu(object):
    def setupUi(self, Adminmenu):
        Adminmenu.setObjectName("Adminmenu")
        Adminmenu.resize(285, 150)
        self.centralwidget = QtWidgets.QWidget(Adminmenu)
        self.centralwidget.setObjectName("centralwidget")
        self.NewuserButton = QtWidgets.QPushButton(self.centralwidget)
        self.NewuserButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.NewuserButton.setObjectName("NewuserButton")
        self.ListofusersButton = QtWidgets.QPushButton(self.centralwidget)
        self.ListofusersButton.setGeometry(QtCore.QRect(30, 40, 75, 23))
        self.ListofusersButton.setObjectName("ListofusersButton")
        self.ChangepassButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChangepassButton.setGeometry(QtCore.QRect(50, 70, 75, 23))
        self.ChangepassButton.setObjectName("ChangepassButton")
        self.ChooseoptionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseoptionsButton.setGeometry(QtCore.QRect(160, 10, 91, 23))
        self.ChooseoptionsButton.setObjectName("ChooseoptionsButton")
        self.AboutButton = QtWidgets.QPushButton(self.centralwidget)
        self.AboutButton.setGeometry(QtCore.QRect(170, 40, 75, 23))
        self.AboutButton.setObjectName("AboutButton")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(170, 70, 75, 23))
        self.Exit.setObjectName("Exit")
        self.MagicsquareButton = QtWidgets.QPushButton(self.centralwidget)
        self.MagicsquareButton.setGeometry(QtCore.QRect(70, 100, 91, 23))
        self.MagicsquareButton.setObjectName("MagicsquareButton")
        self.Yourname = QtWidgets.QLabel(self.centralwidget)
        self.Yourname.setGeometry(QtCore.QRect(190, 100, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Yourname.setFont(font)
        self.Yourname.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Yourname.setText("")
        self.Yourname.setTextFormat(QtCore.Qt.AutoText)
        self.Yourname.setPixmap(QtGui.QPixmap("ui\\../admin.jpg"))
        self.Yourname.setScaledContents(True)
        self.Yourname.setObjectName("Yourname")
        Adminmenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Adminmenu)
        QtCore.QMetaObject.connectSlotsByName(Adminmenu)

    def retranslateUi(self, Adminmenu):
        _translate = QtCore.QCoreApplication.translate
        Adminmenu.setWindowTitle(_translate("Adminmenu", "Admin menu"))
        self.NewuserButton.setText(_translate("Adminmenu", "New user"))
        self.ListofusersButton.setText(_translate("Adminmenu", "List of users"))
        self.ChangepassButton.setText(_translate("Adminmenu", "Change pass"))
        self.ChooseoptionsButton.setText(_translate("Adminmenu", "Choose options"))
        self.AboutButton.setText(_translate("Adminmenu", "About"))
        self.Exit.setText(_translate("Adminmenu", "Exit"))
        self.MagicsquareButton.setText(_translate("Adminmenu", "Magic square"))
        self.Yourname.setToolTip(_translate("Adminmenu", "<html><head/><body><p><img src=\":/img/E:/Downloads/b84109409ef58f7bbcd819f54acb5107.jpg\"/></p></body></html>"))
import res_rc
