# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Entering.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Entering(object):
    def setupUi(self, Entering):
        Entering.setObjectName("Entering")
        Entering.resize(285, 150)
        self.centralwidget = QtWidgets.QWidget(Entering)
        self.centralwidget.setObjectName("centralwidget")
        self.Userslist = QtWidgets.QComboBox(self.centralwidget)
        self.Userslist.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Userslist.setFont(font)
        self.Userslist.setObjectName("Userslist")
        self.Passwordform = QtWidgets.QLineEdit(self.centralwidget)
        self.Passwordform.setGeometry(QtCore.QRect(10, 50, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Passwordform.setFont(font)
        self.Passwordform.setObjectName("Passwordform")
        self.Enter = QtWidgets.QPushButton(self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(100, 92, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Enter.setFont(font)
        self.Enter.setObjectName("Enter")
        Entering.setCentralWidget(self.centralwidget)

        self.retranslateUi(Entering)
        QtCore.QMetaObject.connectSlotsByName(Entering)

    def retranslateUi(self, Entering):
        _translate = QtCore.QCoreApplication.translate
        Entering.setWindowTitle(_translate("Entering", "Entering"))
        self.Passwordform.setPlaceholderText(_translate("Entering", "Password..."))
        self.Enter.setText(_translate("Entering", "Enter"))
