# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Listofusers_msg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Listofusers(object):
    def setupUi(self, Listofusers):
        Listofusers.setObjectName("Listofusers")
        Listofusers.resize(285, 150)
        self.centralwidget = QtWidgets.QWidget(Listofusers)
        self.centralwidget.setObjectName("centralwidget")
        self.deleteuserButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteuserButton.setGeometry(QtCore.QRect(20, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteuserButton.setFont(font)
        self.deleteuserButton.setObjectName("deleteuserButton")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(150, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Back.setFont(font)
        self.Back.setObjectName("Back")
        self.Userslist = QtWidgets.QComboBox(self.centralwidget)
        self.Userslist.setGeometry(QtCore.QRect(10, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Userslist.setFont(font)
        self.Userslist.setObjectName("Userslist")
        self.Options = QtWidgets.QPushButton(self.centralwidget)
        self.Options.setGeometry(QtCore.QRect(20, 55, 75, 23))
        self.Options.setObjectName("Options")
        self.USB = QtWidgets.QPushButton(self.centralwidget)
        self.USB.setGeometry(QtCore.QRect(186, 55, 75, 23))
        self.USB.setObjectName("USB")
        self.Messege = QtWidgets.QPushButton(self.centralwidget)
        self.Messege.setGeometry(QtCore.QRect(103, 55, 75, 23))
        self.Messege.setObjectName("Messege")
        Listofusers.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Listofusers)
        self.statusbar.setObjectName("statusbar")
        Listofusers.setStatusBar(self.statusbar)

        self.retranslateUi(Listofusers)
        QtCore.QMetaObject.connectSlotsByName(Listofusers)

    def retranslateUi(self, Listofusers):
        _translate = QtCore.QCoreApplication.translate
        Listofusers.setWindowTitle(_translate("Listofusers", "List of users"))
        self.deleteuserButton.setText(_translate("Listofusers", "Delete user"))
        self.Back.setText(_translate("Listofusers", "Back"))
        self.Options.setText(_translate("Listofusers", "Options"))
        self.USB.setText(_translate("Listofusers", "USB"))
        self.Messege.setText(_translate("Listofusers", "Messege"))
