# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Newuserform2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Newuserform(object):
    def setupUi(self, Newuserform):
        Newuserform.setObjectName("Newuserform")
        Newuserform.resize(285, 150)
        self.centralwidget = QtWidgets.QWidget(Newuserform)
        self.centralwidget.setObjectName("centralwidget")
        self.Newusername = QtWidgets.QLineEdit(self.centralwidget)
        self.Newusername.setGeometry(QtCore.QRect(10, 10, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Newusername.setFont(font)
        self.Newusername.setObjectName("Newusername")
        self.Newusersubmit = QtWidgets.QPushButton(self.centralwidget)
        self.Newusersubmit.setGeometry(QtCore.QRect(20, 70, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Newusersubmit.setFont(font)
        self.Newusersubmit.setObjectName("Newusersubmit")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(150, 70, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Back.setFont(font)
        self.Back.setObjectName("Back")
        Newuserform.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Newuserform)
        self.statusbar.setObjectName("statusbar")
        Newuserform.setStatusBar(self.statusbar)

        self.retranslateUi(Newuserform)
        QtCore.QMetaObject.connectSlotsByName(Newuserform)

    def retranslateUi(self, Newuserform):
        _translate = QtCore.QCoreApplication.translate
        Newuserform.setWindowTitle(_translate("Newuserform", "New user form"))
        self.Newusername.setPlaceholderText(_translate("Newuserform", "New user name..."))
        self.Newusersubmit.setText(_translate("Newuserform", "Submit"))
        self.Back.setText(_translate("Newuserform", "Back"))
