# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Outputform.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Outputform(object):
    def setupUi(self, Outputform):
        Outputform.setObjectName("Outputform")
        Outputform.resize(285, 150)
        self.textBrowser = QtWidgets.QTextBrowser(Outputform)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 261, 121))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Outputform)
        QtCore.QMetaObject.connectSlotsByName(Outputform)

    def retranslateUi(self, Outputform):
        _translate = QtCore.QCoreApplication.translate
        Outputform.setWindowTitle(_translate("Outputform", "Output form"))
