# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/USBAccess.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_USBAccess(object):
    def setupUi(self, USBAccess):
        USBAccess.setObjectName("USBAccess")
        USBAccess.resize(285, 150)
        self.GiveaccessButton = QtWidgets.QPushButton(USBAccess)
        self.GiveaccessButton.setGeometry(QtCore.QRect(20, 65, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GiveaccessButton.setFont(font)
        self.GiveaccessButton.setObjectName("GiveaccessButton")
        self.Back = QtWidgets.QPushButton(USBAccess)
        self.Back.setGeometry(QtCore.QRect(150, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Back.setFont(font)
        self.Back.setObjectName("Back")
        self.USBlist = QtWidgets.QComboBox(USBAccess)
        self.USBlist.setGeometry(QtCore.QRect(10, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.USBlist.setFont(font)
        self.USBlist.setObjectName("USBlist")
        self.DenyaccessButton = QtWidgets.QPushButton(USBAccess)
        self.DenyaccessButton.setGeometry(QtCore.QRect(20, 110, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DenyaccessButton.setFont(font)
        self.DenyaccessButton.setObjectName("DenyaccessButton")

        self.retranslateUi(USBAccess)
        QtCore.QMetaObject.connectSlotsByName(USBAccess)

    def retranslateUi(self, USBAccess):
        _translate = QtCore.QCoreApplication.translate
        USBAccess.setWindowTitle(_translate("USBAccess", "USB Access form"))
        self.GiveaccessButton.setText(_translate("USBAccess", "Give access"))
        self.Back.setText(_translate("USBAccess", "Back"))
        self.DenyaccessButton.setText(_translate("USBAccess", "Deny access"))
