# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Userspace.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Userspace(object):
    def setupUi(self, Userspace):
        Userspace.setObjectName("Userspace")
        Userspace.resize(285, 150)
        self.centralwidget = QtWidgets.QWidget(Userspace)
        self.centralwidget.setObjectName("centralwidget")
        self.Username = QtWidgets.QTextBrowser(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(90, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Username.setFont(font)
        self.Username.setObjectName("Username")
        self.Yourname = QtWidgets.QLabel(self.centralwidget)
        self.Yourname.setGeometry(QtCore.QRect(20, 20, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Yourname.setFont(font)
        self.Yourname.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Yourname.setObjectName("Yourname")
        self.ChangepassButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChangepassButton.setGeometry(QtCore.QRect(20, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ChangepassButton.setFont(font)
        self.ChangepassButton.setObjectName("ChangepassButton")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(150, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Exit.setFont(font)
        self.Exit.setObjectName("Exit")
        Userspace.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Userspace)
        self.statusbar.setObjectName("statusbar")
        Userspace.setStatusBar(self.statusbar)

        self.retranslateUi(Userspace)
        QtCore.QMetaObject.connectSlotsByName(Userspace)

    def retranslateUi(self, Userspace):
        _translate = QtCore.QCoreApplication.translate
        Userspace.setWindowTitle(_translate("Userspace", "User space"))
        self.Yourname.setText(_translate("Userspace", "Your \n"
"name"))
        self.ChangepassButton.setText(_translate("Userspace", "Change pass"))
        self.Exit.setText(_translate("Userspace", "Exit"))
